### ISSUE TITLE
Cannot run main.py, no such file error

### ISSUE THREAD

**Issue by spectromas** [ybgirgin3/KDynamic#1]
Perhaps I'm missing something but if I run `python3 main.py` I get the following error:

```
python3 main.py
light_dark mode activating -- wallpaper changing
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    main()
  File "main.py", line 75, in main
    command1 = light_dark(isDark = False)
  File "/home/alex/.git_repos/KDynamic/light_dark.py", line 44, in light_dark
    plasma_themes(light_plasma_theme)
  File "/home/alex/.git_repos/KDynamic/light_dark.py", line 16, in plasma_themes
    with open(txt_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '{}/KDynamic/light_plasma_theme.txt'
```

I have added some images and put 'Breeze' and Breeze-Dark' in the theme files but even with a clean setup I get this error.

**Comment by ybgirgin3** [comment]
First you need to run 'setup.py' file this will create 'KDynamic/light_plasma_theme.txt' and other needed files and folders. 

> I have added some images and put 'Breeze' and Breeze-Dark' in the theme files

you need to add images to KDynamic/Pictures/light, KDynamic/Pictures/light_dark and KDynamic/Pictures/night folder

this must work.. thanks by the way :)

**Comment by spectromas** [comment]
I did run the setup first , it created: 

```
[alex ~/KDynamic] ls
./  ../  light_plasma_theme.txt  night_plasma_theme.txt  Pictures/
```

but the above error is what I get. 

`FileNotFoundError: [Errno 2] No such file or directory: '{}/KDynamic/light_plasma_theme.txt'` is the variable for home set correctly? The directory and file is there in my home directory.

**Comment by ybgirgin3** [comment]
I just eyeballed program and there was a little misspelling and I changed it excuse me :)

**Comment by spectromas** [comment]
No worries! I'm getting this now: 

```
[alex ~/.git_repos/KDynamic][master] python3 main.py
light_dark mode activating -- wallpaper changing
sh: 1: Syntax error: "(" unexpected
isDark = True
```

**Comment by ybgirgin3** [comment]
inside the light_dark.txt command must be like that can you compare with yours ??

> qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file:///home/berkay/KDynamic/Pictures/light_dark/alligator.jpg")}'

**Comment by spectromas** [comment]
I didn't realise that had to be edited, it is working now. Thank you for making this and for the help getting started!
