### ISSUE TITLE
Great project.

### ISSUE THREAD

**Issue by Professor-Paradox** [ybgirgin3/KDynamic#2]
I wanted something similar for my ubuntu kde installation. But didn't find any thing that can do this.   
Found a plugin called plasmadesktopsaver but that takes too long and stores every file to memory. needed an alternative for that. 
So created my own after creating my own repo to change themes based on time,I found your repo,looks great and is interesting. 
While you created using python i used bash.So any tips,suggestions on my own repo would be helpful for further improvement. https://github.com/Professor-Paradox/KdeAutoThemeSwitch

**Comment by ybgirgin3** [comment]
your repo looks great man!!.. thanks for contribition, maybe I can get some knowledge about native plasma commands from your scripts. looks like you search deeply before writing scripts. Excellent job !. I think you need to share your repo in reddit or somewhere like i did before here is link my reddit post:  https://www.reddit.com/r/kde/comments/d008s0/hello_everyone_i_created_a_simple_dynamic/
